version: "3.7"

services:
    db:
        image: postgres:13.1
        env_file:
            - ./.env
        volumes:
            - db_data:/var/lib/postgresql/data/

    django:
        env_file:
            - ./.env
        volumes:
            - static_files:/app/static
        build:
            context: .
            dockerfile: docker/prod/Dockerfile.django.prod
        command: ./docker/prod/django_setup_prod.sh
        expose:
            - 8000
        depends_on:
            - db
        restart: always

    nginx:
        build:
            context: .
            dockerfile: docker/prod/Dockerfile.nginx.prod
        volumes:
            - static_files:/app/static
        ports:
            - 80:80
        depends_on:
            - django
        restart: always

volumes:
    db_data:
    static_files:
